name: "Jest GitHub Action with shard support"
author: "Ishan Madhusanka (ahtimadhusanka@gmail.com)"
description: "Runs Jest with shard support and merges collected coverage"
inputs:
  github-token:
    description: "Github Token for the workflow"
    default: "GITHUB_TOKEN"
    required: true
  command:
    description: "Command to run (one of 'run-tests' | 'merge-coverage'"
    required: false
    default: "run-tests"
  coverage:
    description: "Enable Coverage for`run-tests` command"
    required: false
    default: "true"
  shard:
    description: "Jest shard to be executed for`run-tests` command (eg: `1/4`) "
    required: false
    default: "1/1"
  skip-artifact-upload:
    description: "Avoid uploading coverage results, if all the actions are running in a single step"
    required: false
    default: "false"
  show-all-files-in-summary:
    description: "Shows coverage information of all files, along with the summary"
    required: false
    default: "false"
  shard-count:
    description: "Shard count need to be defined `merge-coverage` command"
    required: false
    default: "1"
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "check-circle"
  color: "purple"
