name: "Hello Actions"
description: "Greet someone and record the time"
inputs:
  action-secret:
    description: "Github Token"
    required: true
  command:
    description: "Action to run (eg: 'run-tests' | 'merge-coverage'"
    required: true
    default: "run-tests"
  coverage:
    description: "Enable Coverage"
    required: true
    default: "true"
  shard:
    description: "Shard to run (eg: '1/4')"
    required: false
    default: "1/1"
runs:
  using: "node16"
  main: "dist/index.js"
