name: "test"
on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: [1/2, 2/2]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - uses: ./
        name: "Run tests ${{ matrix.shard }}"
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          task: "run-tests"
          shard: ${{ matrix.shard }}
          coverage: true

  merge-coverage:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - uses: ./
        name: "Merge Coverage"
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          task: "merge-coverage"
          shard-count: "2"
          show-all-files-in-summary: true
